### ISSUE TITLE
System not Function by Post Request

### ISSUE THREAD

**Issue by Codename-Beast** [hakanersu/amaran-laravel#1]
The Notifaction dons't work when Post request complete

**Comment by hakanersu** [comment]
I will check as soon as possible.

**Comment by avlastenok** [comment]
@Codename-Beast what exactly does not work with the Post request ?
Done some testing here on post, put, get everything seems to work as expected.
Did you reset your cache files after updating your master file ?

**Comment by avlastenok** [comment]
It does not seem to be the Post request but due to the redirect()
Made a few attempts at this if I return a view just after a post request it shows the notification just as expected however if I want to redirect the user just after their post request as you'd actually want to do
the notification never shows up.

**Comment by hakanersu** [comment]
i cant reproduce problem can you give any little example ?

**Comment by avlastenok** [comment]
public function create()
{
  return view('form');
}

that form is set to post to etc store function

public function store()
{
I will then add the notification here as I do not want a notification on the index every time that page is loaded but only when data have been inserted or failed to insert.
Amaran::content(['message' => 'Article created'])
    ->position('top right')
    ->inEffect('slideRight')
    ->outEffect('slideRight')
    ->create();
  do your validate and insert to db then
redirect()->route('home');
}

Lets say that the home route is index
public function index()
{
 retuen view('home');
}

it does seem like it does not auto set a session flash, implementing it myself atm. however that is something a notification package really should have.

**Comment by hakanersu** [comment]
Yes, as you notice im not impelement session like laravel flash messages.But i will add that feature like;

```
Amaran::content(['message'=>'Hello World'])->flash()->create();
```

As for now you can use like that;

```
public function store()
{
    if($stored)
    {
        Session::flash('store',true);
    }
}

public function index()
{
    if(Session::get('store'))
    {
        Amaran::content(['message'=>'Hello World'])->create();
    }
    return view('home');
}
```

**Comment by hakanersu** [comment]
Hey guys i added flash method you can use like this;

Just add flash method.

```
Amaran::content(['message'=>'Hello World'])->flash()->create();
```
