### ISSUE TITLE
Not working after redirect~

### ISSUE THREAD

**Issue by woodytang** [hakanersu/amaran-laravel#2]
This is an awesome package i'v been looking for ~ just, as the title mentioned, Not working after redirect~~it works on normal view rendering though.

I guess you pass values to view which works fine while when redirected it requires session data which may have not been set yet.

**Comment by hakanersu** [comment]
@woodytang can you provide an example ? 

This code below works fine.I guess problem a bit diffrent from this example.

```
public function test()
{
    Session::put('anahtar', 'Lorem dis bu');
    return Redirect::to('amaranjs-page);
}

public function amaranjs-page()
{
     Amaran::content(['message'=>Session::get('anahtar')])->create();
}
```

I'll try to implement session feature.

**Comment by woodytang** [comment]
thanks, this should works fine~~
Yeah, a session auto-set-and-get will make it prefect! :)

**Comment by hakanersu** [comment]
Hey i added flash method you can use like this;

Just add flash method.

```
Amaran::content(['message'=>'Hello World'])->flash()->create();
```

**Comment by woodytang** [comment]
thats awesome, definitely will try it!

Date: Sat, 14 Feb 2015 04:46:48 -0800
