### ISSUE TITLE
Publish config file

### ISSUE THREAD

**Issue by nicozimmermann94** [hakanersu/amaran-laravel#4]
Hey,
it would be very nice if your package contains a config file where you can put defaults like theme name, default method (flash / no flash) etc in it.
This way I do not have to write every time things like ...flash()->...
Cheers

**Comment by hakanersu** [comment]
i'll try to update soon.

**Comment by nicozimmermann94** [comment]
Maybe an update on this? ^^

**Comment by hakanersu** [comment]
Update your composer.json with
```
"xuma/laravel-amaran": "1.1.0"
```
than you can publish configuration

```
php artisan vendor:publish --provider="Xuma\Amaran\AmaranServiceProvider" --tag="config"
```
Config file includes basic amaranjs configuration options.

```php
<?php

return [
    'theme' => 'default',
    'position' => 'top left',
    'inEffect' => 'slideRight',
    'outEffect' => 'slideRight',
    'sticky' => false
];

```

I know its a late update but i was a bit busy last year.

**Comment by nicozimmermann94** [comment]
Thank you! Is it possible to set 'flash' to true/false?

**Comment by nicozimmermann94** [comment]
Maybe you can take a look at my pr

**Comment by hakanersu** [comment]
Thanks 👍
